export interface IAuthor {
    "userProfileId": number;
    "profile": {
        subscriberUserId?: number;
        subscriberUser?: string;
        authorUserId?: number;
        authorUser?: string;
        webAdminUserId?: number;
        webAdminUser?: string;
        fullName?: string;
        name?: string;
        surnameP?: string;
        surnameM?: string;
        profileImageUrl?: string;
        profileImagePath?: string;
        email?: string;
        profileImageUploadDate?: string;
        id?: number;
        createdDate?: string;
        updatedDate?: string;
        isDeleted?: boolean;
    },
    dateJoined?: string;
    displayName?: string;
    introText?: string;
    socialMedia?: any;
    newsArticles?: any;
    createdDate?: string;
    updatedDate?: string;
    accountStatus?: string;
    userRoles?: any[];
    socials?: any[];
    id?: number;
    userName?: string;
    normalizedUserName?: string;
    email?: string;
    normalizedEmail?: string;
    emailConfirmed?: boolean;
    passwordHash?: string;
    securityStamp?: string;
    concurrencyStamp?: string;
    phoneNumber?: string;
    phoneNumberConfirmed?: boolean;
    twoFactorEnabled?: boolean;
    lockoutEnd?: any;
    lockoutEnabled?: string;
    accessFailedCount?: number;
}